### ISSUE TITLE
Estimate episode dates more accurately

### ISSUE THREAD

**Issue by loucasal** [timendum/raiplaysound#3] opened 2022-10-09 10:40 UTC
Some feeds (e.g. [Wikiradio](https://timendum.github.io/raiplaysound/wikiradio.xml)) seem to use the scraping date as episode date. As a consequence, all episodes currently appear with the same date.

At least for this podcast, it should be possible to retrieve dates more accurately based on the URL of the episode.

**Comment by timendum** [comment] 2022-10-10 10:00
You are correct, this was because of a b18b2b3d9b7e4c2f7a28022caae7d96ef41ef087, where we tried to fix incorrect dates.

The problem is:
- daily o frequent podcast are ordered from newer to older (es: wikiradio)
- audiobooks or on-off programs are from older to newer

I can't find a way to distinguish between these two cases, and the default now, is the second one.

Probably a commit older then b18b2b3d9b7e4c2f7a28022caae7d96ef41ef087, should work.

Any suggestion is appreciated.

**Comment by timendum** [comment] 2023-08-09 09:14
It should be fixed, if not, use `--dateok` on `single.py` to keep original datetime.

**Closed as completed by timendum** 2023-08-09 09:14 UTC
